version: '3.7'

services:
  freeipa:
    command:
      - no-exit #useful for debugging
    container_name: fipa-server
    environment:
      - IPA_SERVER_HOSTNAME=${IPA_SERVER_HOSTNAME:-fipa-server}.${DOMAIN:-internal}
    image: freeipa/freeipa-server:centos-7
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.lo.disable_ipv6=0
    tmpfs:
      - /run
      - /tmp
    volumes:
      - ${VOLUME_ROOT:-./volumes}/freeipa/data:/data
      - ${VOLUME_ROOT:-./volumes}/freeipa/logs:/var/log
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
