version: '3.7'

services:
  agent-centos:
    build:
      context: agent/centos
      args:
        - CENTOS_VERSION
        - CENTOS_VERSION_MAJOR
        - PUPPETAGENT_CERTNAME
        - PUPPETAGENT_VERSION_MAJOR
    container_name: ${PUPPET_AGENT_CERTNAME:-agent-centos-1}
    depends_on: [ puppet ]
    hostname: ${PUPPET_AGENT_CERTNAME:-agent-centos-1}.${DOMAIN:-internal}
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
